-- Scripts para criação do projeto --

CREATE TABLE usuario (
	cpf VARCHAR(100) NOT NULL,
	nome VARCHAR(100) NOT NULL,
  	senha VARCHAR(100) NOT NULL,
 	PRIMARY KEY (cpf) 
);

CREATE TABLE FEIRA 
(
  ID NUMBER NOT NULL 
, NOME VARCHAR2(100) NOT NULL 
, DATA DATE NOT NULL 
, OBSERVACAO VARCHAR2(500) NOT NULL 
, CONSTRAINT FEIRA_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

CREATE TABLE TABLE1 
(
  ID NUMBER NOT NULL 
, NOME VARCHAR2(100) NOT NULL 
, QUANTIDADE NUMBER NOT NULL 
, UNIDADE VARCHAR2(100) NOT NULL 
, ID_FEIRA NUMBER NOT NULL 
, CONSTRAINT TABLE1_PK PRIMARY KEY 
  (
    ID 
  )
  ENABLE 
);

ALTER TABLE ITEM_FEIRA
ADD FOREIGN KEY (ID_FEIRA) 
REFERENCES FEIRA(ID);

CREATE SEQUENCE  S_FEIRA  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE  S_ITEM_FEIRA  MINVALUE 1 MAXVALUE 999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
   